# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  name: app
  group: app
  replicaCount: 1
  container:
    image: dkfolefac/wordapi:67
    port: 8080
    env:
       - key: key
         value: value
  service:
    type: NodePort
    port: 8081